<?php
include(__DIR__."/adminuser/class/AdminuserController.php");
include(__DIR__."/adminuser/class/AdminuserModel.php");
include(__DIR__."/modules/class/ModulesController.php");
include(__DIR__."/modules/class/ModulesModel.php");
include(__DIR__."/plugins/class/PluginsController.php");
include(__DIR__."/plugins/class/PluginsModel.php");
include(__DIR__."/settings/class/SettingsController.php");
include(__DIR__."/settings/class/SettingsModel.php");
?>